services:
  - type: web
    name: cheemy-bot
    runtime: node
    repo: https://github.com/Hendrix-D-Dev/cheemy-bot
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm run render
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: BOT_NUMBER
        value: 2349043650490
      - key: PREFIX
        value: .
      - key: ADMIN_NUMBERS
        value: 2349043650490
      - key: ENABLE_AI
        value: false
      - key: FORCE_NEW_AUTH
        value: true
      - key: AUTO_PAIR
        value: true
      - key: AUTH_CLEAR_SECRET
        generateValue: true
      - key: RENDER_DEPLOY
        value: true

cron:
  - name: keep-bot-alive
    schedule: "*/10 * * * *"
    command: curl -I https://cheemy-bot.onrender.com/ping